# Generated by Django 4.2 on 2026-04-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('accountid', models.TextField(primary_key=True, serialize=False)),
                ('senderuser', models.TextField(default='message ai')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
