# Generated by Django 4.2 on 2026-04-08 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_message_created_at_alter_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Generate_status', models.BooleanField(default=False)),
            ],
        ),
    ]
