# Generated by Django 4.2 on 2026-04-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='accountid',
            field=models.TextField(default='AnonymousUser'),
        ),
    ]
