# Generated by Django 4.2 on 2026-04-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_status_accountid'),
    ]

    operations = [
        migrations.CreateModel(
            name='EternalMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountid', models.TextField(default='AnonymousUser')),
                ('Memory', models.TextField(default='')),
            ],
        ),
    ]
