# Generated by Django 4.2 on 2026-04-08 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_eternalmemory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EternalMemory',
        ),
    ]
