# Generated by Django 4.2 on 2026-04-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_message_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountid', models.TextField(default='AnonymousUser')),
                ('chats', models.TextField(default='')),
            ],
        ),
    ]
