# Generated by Django 4.2 on 2026-04-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_chats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='chats',
            new_name='chat',
        ),
    ]
