# Generated by Django 4.2 on 2026-04-08 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_chats_chats_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chat_id',
            new_name='chatid',
        ),
    ]
