# Generated by Django 4.2 on 2026-04-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_chat_id_message_chatid'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='chatid',
            field=models.TextField(default=''),
        ),
    ]
