# Generated by Django 4.2 on 2026-04-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_chats_chatid'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='currentchat',
            field=models.TextField(default='none'),
        ),
    ]
