# Generated by Django 4.2 on 2026-04-08 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_status_currentchat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='chat',
            new_name='chatname',
        ),
    ]
