# Generated by Django 4.2 on 2026-04-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_chat_chats_chatname'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='messageid',
            field=models.IntegerField(default=0),
        ),
    ]
