# Generated by Django 4.2 on 2026-04-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_message_messageid'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
