# Generated by Django 4.2 on 2026-04-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_chats_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='last_message',
            field=models.TextField(default=''),
        ),
    ]
