# Generated by Django 4.2 on 2026-04-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_chats_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='avatar',
            field=models.TextField(default=''),
        ),
    ]
