# Generated by Django 4.2 on 2026-04-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_chats_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='AI_Prompt',
            field=models.TextField(default=''),
        ),
    ]
