# Generated by Django 4.2 on 2026-04-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_chats_ai_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
