# Generated by Django 4.2 on 2026-04-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_chats_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='is_read',
            field=models.BooleanField(default=True),
        ),
    ]
