# Generated by Django 4.2 on 2026-04-30 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_chats_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='is_read',
            new_name='is_rp',
        ),
    ]
