# Generated by Django 4.2 on 2026-05-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_rename_is_read_chats_is_rp'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='AI_Name',
            field=models.TextField(default=''),
        ),
    ]
