# Generated by Django 4.2 on 2026-05-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_chats_ai_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountid', models.TextField(default='AnonymousUser')),
                ('CustomInstructions', models.TextField(default='')),
                ('Name', models.TextField(default='')),
                ('Occupation', models.TextField(default='')),
                ('Interests', models.TextField(default='')),
            ],
        ),
    ]
