# Generated by Django 4.2 on 2026-05-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_customization'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='CustomInstructions',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='chats',
            name='Interests',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='chats',
            name='Name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='chats',
            name='Occupation',
            field=models.TextField(default=''),
        ),
    ]
