# Generated by Django 4.2 on 2026-05-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_chats_custominstructions_chats_interests_chats_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='Ban_status',
            field=models.BooleanField(default=False),
        ),
    ]
