# Generated by Django 4.2 on 2026-05-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_status_ban_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='Emoji',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customization',
            name='Emoji',
            field=models.TextField(default=''),
        ),
    ]
