# Generated by Django 4.2 on 2026-05-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_chats_emoji_customization_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='AI_Name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='chats',
            name='AI_Prompt',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='chats',
            name='CustomInstructions',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='chats',
            name='Emoji',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='chats',
            name='Interests',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='chats',
            name='Name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='chats',
            name='Occupation',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='chats',
            name='is_rp',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='chats',
            name='summary',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='accountid',
            field=models.TextField(default='AnonymousUser'),
        ),
    ]
