# Generated by Django 4.2 on 2026-05-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_chats_ai_name_alter_chats_ai_prompt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='Ban_status',
            new_name='is_banned',
        ),
    ]
