# Generated by Django 4.2 on 2026-05-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_rename_ban_status_status_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='is_VIP',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='is_developer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
