# Generated by Django 4.2 on 2026-05-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_status_is_vip_status_is_developer_status_is_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='is_VIP',
        ),
        migrations.RemoveField(
            model_name='status',
            name='is_banned',
        ),
        migrations.RemoveField(
            model_name='status',
            name='is_developer',
        ),
        migrations.RemoveField(
            model_name='status',
            name='is_owner',
        ),
        migrations.AddField(
            model_name='status',
            name='AccessLevel',
            field=models.TextField(default='User'),
        ),
    ]
