# Generated by Django 4.2 on 2026-05-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_remove_status_is_vip_remove_status_is_banned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='AccessLevel',
        ),
        migrations.AddField(
            model_name='status',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='is_developer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
