# Generated by Django 4.2 on 2026-05-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_remove_status_accesslevel_status_is_banned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='is_VIP',
            field=models.BooleanField(default=False),
        ),
    ]
