# Generated by Django 4.2 on 2026-05-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_status_is_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
