# Generated by Django 4.2 on 2026-06-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_chats_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountid', models.TextField(default='AnonymousUser')),
                ('ProfilePicture', models.ImageField(default='', upload_to='profile_pics/')),
                ('Name', models.TextField(default='')),
                ('Prompt', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='chats',
            name='ProfilePicture',
            field=models.ImageField(default='', upload_to='profile_pics/'),
        ),
    ]
