# Generated by Django 4.2 on 2026-06-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_characters_chats_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='Description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='characters',
            name='ProfilePicture',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
