# Generated by Django 4.2 on 2026-06-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_characters_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='ProfilePicture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
