# Generated by Django 4.2 on 2026-06-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_characters_avatar_characters_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='OpeningLine',
            field=models.TextField(default=''),
        ),
    ]
