# Generated by Django 4.2 on 2026-06-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_characters_openingline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='ProfilePicture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
