# Generated by Django 4.2 on 2026-06-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_alter_chats_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
