# Generated by Django 4.2 on 2026-06-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_characters_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='CharacterID',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
