# Generated by Django 4.2 on 2026-06-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_chats_characterid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='CharacterID',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
