# Generated by Django 4.2 on 2026-06-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_alter_chats_characterid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='CharacterID',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
