# Generated by Django 4.2 on 2026-06-05 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_alter_chats_characterid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='ProfilePicture',
        ),
    ]
