# Generated by Django 4.2 on 2026-06-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_remove_chats_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
