# Generated by Django 4.2 on 2026-06-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_characters_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='remaining_messages',
            field=models.IntegerField(default=0),
        ),
    ]
