# Generated by Django 4.2 on 2026-06-20 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_status_remaining_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='remaining_messages',
        ),
    ]
