# Generated by Django 4.2 on 2026-06-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_remove_status_remaining_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='remaining_messages',
            field=models.IntegerField(default=100),
        ),
    ]
