# Generated by Django 4.2 on 2026-06-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='user_profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
