# Generated by Django 4.2 on 2026-06-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_status_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='user_profile',
            field=models.ImageField(blank=True, null=True, upload_to='user_profiles/'),
        ),
    ]
