# Generated by Django 4.2 on 2026-06-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_alter_status_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='ProfilePicture',
            field=models.ImageField(blank=True, null=True, upload_to='character_profiles/'),
        ),
    ]
