# Generated by Django 4.2 on 2026-06-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_alter_characters_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='is_limit',
            field=models.BooleanField(default=False),
        ),
    ]
