# Generated by Django 4.2 on 2026-06-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_status_is_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='user_theme',
            field=models.TextField(blank=True, null=True),
        ),
    ]
